mcu: STM32F103
linker:
  useDefault: true
drivers:
  hal: # required
  adc:
  adc_ex:
  can:
  cortex: # required
  dma:
  flash:
  gpio:
  pwr:
  rcc:
  rcc_ex: # required
  spi:
    use_ll: true
  tim:
  tim_ex: # required with tim
