#!/usr/bin/python
from SCons.Script import Import, Return, AddOption, GetOption

Import("*")

try:
    AddOption("--skip-bl", dest="skip-bl", action="store_true")
except:
    pass

if not GetOption("skip-bl"):
    artifacts = SConscript("STM/stm32f1/SConscript", exports=["CONFIG_IDS", "PLATFORM_ENV"])
else:
    artifacts = {}
Return('artifacts')
