load("//sim/infra:defs.bzl", "rig_pytest")

rig_pytest(
    name = "rig_infra",
    test_file = "sim/infra/tests/test_rig.py",
    resources = [
        "//sim/models/test:python",
    ],
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "contracts",
    test_file = "sim/infra/tests/test_contracts.py",
    resources = [
        "//sim/models/test:python",
    ],
    visibility = ["PUBLIC"],
)
