load("//components/shared/code/defs.bzl", "remap_headers")

srcs = glob(["**/*.c", "**/*_FeatureDefs.yaml"])
[
    export_file(
        name = file,
        visibility = ["//components/..."],
    )
    for file in srcs
]

folders = [
    "DRV/",
    "HW/",
    "app/",
    "libs/",
]
exported_headers = remap_headers(folders)

prebuilt_cxx_library(
    name = "headers",
    header_only = True,
    header_namespace = "",
    exported_headers = exported_headers,
    visibility = ["PUBLIC"],
)
