/**
 * MessagePack_generated.c
 * Defines packing functions and packtables for messages
 * This should eventually be autogenerated
 */

#pragma once

/******************************************************************************
 *                             I N C L U D E S
 ******************************************************************************/

#include "BatteryMonitoring.h"
#include "Environment.h"
#include "Cooling.h"
