load("//sim/infra:defs.bzl", "RIG_RUNTIME_RUST_ENV")

rust_test(
    name = "runtime_unit",
    crate = "rig_runtime",
    crate_root = "rust/cluster_lib.rs",
    edition = "2024",
    srcs = glob(["rust/*.rs"]),
    env = {
        name: "$(location {})".format(target)
        for name, target in RIG_RUNTIME_RUST_ENV.items()
    },
    visibility = ["PUBLIC"],
)

export_file(
    name = "runtime-src",
    src = "rust/lib.rs",
    visibility = ["PUBLIC"],
)

[
    export_file(
        name = file,
        src = file,
        visibility = ["PUBLIC"],
    )
    for file in glob(["c/src/*.c", "rust/*.rs"])
]

export_file(
    name = "c/src/runtime_state.h",
    src = "c/src/runtime_state.h",
    visibility = ["PUBLIC"],
)

prebuilt_cxx_library(
    name = "headers",
    header_only = True,
    header_namespace = "",
    exported_headers = {
        header.removeprefix("c/include/"): header
        for header in glob(["c/include/**/*.h"])
    },
    visibility = ["PUBLIC"],
)

genrule(
    name = "runtime-so",
    out = "librig_runtime.so",
    cmd = " ".join([
        "{}=$PWD/$(location {})".format(name, target)
        for name, target in RIG_RUNTIME_RUST_ENV.items()
    ]) +
    " rustc --edition=2024 --crate-name rig_runtime --crate-type cdylib " +
    "$(location :rust/cluster_lib.rs) -o $OUT -C link-arg=-lm",
    visibility = ["PUBLIC"],
)
