mcu: STM32F103
drivers:
  hal: # required
  adc:
  adc_ex:
  can:
  cortex: # required
  dma: # required
  flash: # required
  gpio:
  pwr: # required
  rcc: # required
  rcc_ex: # required
  spi:
    use_ll: true
  tim:
  tim_ex: # required with tim
