on:
  push:
    branches:
      - main

name: Auto Release
jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rust
        with:
          target: ${{ matrix.target }}
      - name: Get Tag
        shell: bash
        run: |
          export GIT_TAG=$(git describe --tags --abbrev=0)
          [[ -z "$GIT_TAG" ]] && GIT_TAG=none
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
      - name: Create Artifact Archive
        id: create-archive
        uses: ./.github/actions/archive
        with:
          target: ${{ matrix.target }}
      # make pre-release for regular pushes
      - if: ${{ env.GIT_TAG == 'none' }}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ steps.create-archive.outputs.archive_name }}
            CHECKSUM
      # make a real release if there's a tag
      - if: ${{ env.GIT_TAG != 'none' }}
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release ${{ github.ref_name }}"
          files: |
            ${{ steps.create-archive.outputs.archive_name }}
            CHECKSUM
