[package]
name = "clock-manager"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "clock-manager"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
