name: Run a Clean and Pull with SHA/SHA7

inputs:
  repo:
    description: "The repo to pull"
    type: string
  ref:
    description: "The ref to pull"
    type: string
outputs:
  sha:
    description: "The current branch's SHA"
    value: ${{ steps.sha.outputs.sha }}
  short-sha:
    description: "The current branch's short (7) SHA"
    value: ${{ steps.sha.outputs.short-sha }}

runs:
  using: "composite"
  steps:
    - name: Pull Branch
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0
        show-progress: 'true'
        submodules: 'recursive'
    - name: Get SHA and SHA7
      shell: bash
      id: sha
      run: |
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT && \
        echo "short-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
