load("//components/vehicle_platform:platforms.bzl", "ALL_PLATFORMS")
load("//sim/infra:defs.bzl", "rig_platform_sim_lib_env", "rig_platform_sim_lib_resources", "rig_platform_variants_env", "rig_pytest")

VCFRONT_MODEL = "//sim/models/controllers/vcfront"
VCPDU_MODEL = "//sim/models/controllers/vcpdu"
VCREAR_MODEL = "//sim/models/controllers/vcrear"
BMSB_MODEL = "//sim/models/controllers/bmsb"
SWS_MODEL = "//sim/models/controllers/sws"

rig_pytest(
    name = "rig_infra",
    test_file = "sim/tests/test_rig_infra.py",
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "runtime_infra",
    test_file = "sim/tests/test_runtime_infra.py",
    env = {
        "VCPDU_ENUMS_PY": "$(location {}:enums-py)".format(VCPDU_MODEL),
        "VCPDU_MODEL_PY": "$(location {}:vcpdu-py)".format(VCPDU_MODEL),
        "VCPDU_SIM_LIB": "$(location {}:sil-so)".format(VCPDU_MODEL),
    } |
    rig_platform_variants_env(ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCPDU", VCPDU_MODEL, ALL_PLATFORMS),
    resources = [
        "{}:enums-py".format(VCPDU_MODEL),
        "{}:vcpdu-py".format(VCPDU_MODEL),
        "{}:sil-so".format(VCPDU_MODEL),
        "//sim/models/components:python",
        "//sim/models/components/asm330:python",
        "//sim/models/components/dc_load:python",
    ] + rig_platform_sim_lib_resources(VCPDU_MODEL, ALL_PLATFORMS),
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "dc_load",
    test_file = "sim/tests/test_dc_load.py",
    resources = [
        "//sim/models/components:python",
        "//sim/models/components/dc_load:python",
    ],
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "component",
    test_file = "sim/tests/test_component.py",
    env = {
        "BMSB_ENUMS_PY": "$(location {}:enums-py)".format(BMSB_MODEL),
        "BMSB_MODEL_PY": "$(location {}:bmsb-py)".format(BMSB_MODEL),
        "BMSB_SIM_LIB": "$(location {}:sil-so)".format(BMSB_MODEL),
        "SWS_ENUMS_PY": "$(location {}:enums-py)".format(SWS_MODEL),
        "SWS_MODEL_PY": "$(location {}:sws-py)".format(SWS_MODEL),
        "SWS_SIM_LIB": "$(location {}:sil-so)".format(SWS_MODEL),
        "VCFRONT_ENUMS_PY": "$(location {}:enums-py)".format(VCFRONT_MODEL),
        "VCFRONT_MODEL_PY": "$(location {}:vcfront-py)".format(VCFRONT_MODEL),
        "VCFRONT_SIM_LIB": "$(location {}:sil-so)".format(VCFRONT_MODEL),
        "VCPDU_ENUMS_PY": "$(location {}:enums-py)".format(VCPDU_MODEL),
        "VCPDU_MODEL_PY": "$(location {}:vcpdu-py)".format(VCPDU_MODEL),
        "VCPDU_SIM_LIB": "$(location {}:sil-so)".format(VCPDU_MODEL),
        "VCREAR_ENUMS_PY": "$(location {}:enums-py)".format(VCREAR_MODEL),
        "VCREAR_MODEL_PY": "$(location {}:vcrear-py)".format(VCREAR_MODEL),
        "VCREAR_SIM_LIB": "$(location {}:sil-so)".format(VCREAR_MODEL),
    } |
    rig_platform_variants_env(ALL_PLATFORMS) |
    rig_platform_sim_lib_env("BMSB", BMSB_MODEL, ALL_PLATFORMS) |
    rig_platform_sim_lib_env("SWS", SWS_MODEL, ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCFRONT", VCFRONT_MODEL, ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCPDU", VCPDU_MODEL, ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCREAR", VCREAR_MODEL, ALL_PLATFORMS),
    resources = [
        "{}:enums-py".format(BMSB_MODEL),
        "{}:bmsb-py".format(BMSB_MODEL),
        "{}:sil-so".format(BMSB_MODEL),
        "{}:enums-py".format(SWS_MODEL),
        "{}:sws-py".format(SWS_MODEL),
        "{}:sil-so".format(SWS_MODEL),
        "{}:enums-py".format(VCFRONT_MODEL),
        "{}:vcfront-py".format(VCFRONT_MODEL),
        "{}:sil-so".format(VCFRONT_MODEL),
        "{}:enums-py".format(VCPDU_MODEL),
        "{}:vcpdu-py".format(VCPDU_MODEL),
        "{}:sil-so".format(VCPDU_MODEL),
        "{}:enums-py".format(VCREAR_MODEL),
        "{}:vcrear-py".format(VCREAR_MODEL),
        "{}:sil-so".format(VCREAR_MODEL),
        "//sim/models/components:python",
        "//sim/models/components/asm330:python",
        "//sim/models/components/dc_load:python",
    ] +
    rig_platform_sim_lib_resources(BMSB_MODEL, ALL_PLATFORMS) +
    rig_platform_sim_lib_resources(SWS_MODEL, ALL_PLATFORMS) +
    rig_platform_sim_lib_resources(VCFRONT_MODEL, ALL_PLATFORMS) +
    rig_platform_sim_lib_resources(VCPDU_MODEL, ALL_PLATFORMS) +
    rig_platform_sim_lib_resources(VCREAR_MODEL, ALL_PLATFORMS),
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "vcfront_cluster",
    test_file = "sim/tests/test_vcfront.py",
    env = {
        "VCFRONT_ENUMS_PY": "$(location {}:enums-py)".format(VCFRONT_MODEL),
        "VCFRONT_MODEL_PY": "$(location {}:vcfront-py)".format(VCFRONT_MODEL),
        "VCFRONT_SIM_LIB": "$(location {}:sil-so)".format(VCFRONT_MODEL),
    } |
    rig_platform_variants_env(ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCFRONT", VCFRONT_MODEL, ALL_PLATFORMS),
    resources = [
        "{}:enums-py".format(VCFRONT_MODEL),
        "{}:vcfront-py".format(VCFRONT_MODEL),
        "{}:sil-so".format(VCFRONT_MODEL),
    ] + rig_platform_sim_lib_resources(VCFRONT_MODEL, ALL_PLATFORMS),
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "vcpdu_cluster",
    test_file = "sim/tests/test_vcpdu.py",
    env = {
        "VCPDU_ENUMS_PY": "$(location {}:enums-py)".format(VCPDU_MODEL),
        "VCPDU_MODEL_PY": "$(location {}:vcpdu-py)".format(VCPDU_MODEL),
        "VCPDU_SIM_LIB": "$(location {}:sil-so)".format(VCPDU_MODEL),
    } |
    rig_platform_variants_env(ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCPDU", VCPDU_MODEL, ALL_PLATFORMS),
    resources = [
        "{}:enums-py".format(VCPDU_MODEL),
        "{}:vcpdu-py".format(VCPDU_MODEL),
        "{}:sil-so".format(VCPDU_MODEL),
        "//sim/models/components:python",
        "//sim/models/components/asm330:python",
        "//sim/models/components/dc_load:python",
    ] + rig_platform_sim_lib_resources(VCPDU_MODEL, ALL_PLATFORMS),
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "vcrear_cluster",
    test_file = "sim/tests/test_vcrear.py",
    env = {
        "VCREAR_ENUMS_PY": "$(location {}:enums-py)".format(VCREAR_MODEL),
        "VCREAR_MODEL_PY": "$(location {}:vcrear-py)".format(VCREAR_MODEL),
        "VCREAR_SIM_LIB": "$(location {}:sil-so)".format(VCREAR_MODEL),
    } |
    rig_platform_variants_env(ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCREAR", VCREAR_MODEL, ALL_PLATFORMS),
    resources = [
        "{}:enums-py".format(VCREAR_MODEL),
        "{}:vcrear-py".format(VCREAR_MODEL),
        "{}:sil-so".format(VCREAR_MODEL),
    ] + rig_platform_sim_lib_resources(VCREAR_MODEL, ALL_PLATFORMS),
    visibility = ["PUBLIC"],
)

rig_pytest(
    name = "vehicle_cluster",
    test_file = "sim/tests/test_vehicle.py",
    env = {
        "VCFRONT_ENUMS_PY": "$(location {}:enums-py)".format(VCFRONT_MODEL),
        "VCFRONT_MODEL_PY": "$(location {}:vcfront-py)".format(VCFRONT_MODEL),
        "VCFRONT_SIM_LIB": "$(location {}:sil-so)".format(VCFRONT_MODEL),
        "VCPDU_ENUMS_PY": "$(location {}:enums-py)".format(VCPDU_MODEL),
        "VCPDU_MODEL_PY": "$(location {}:vcpdu-py)".format(VCPDU_MODEL),
        "VCPDU_SIM_LIB": "$(location {}:sil-so)".format(VCPDU_MODEL),
        "VCREAR_ENUMS_PY": "$(location {}:enums-py)".format(VCREAR_MODEL),
        "VCREAR_MODEL_PY": "$(location {}:vcrear-py)".format(VCREAR_MODEL),
        "VCREAR_SIM_LIB": "$(location {}:sil-so)".format(VCREAR_MODEL),
    } |
    rig_platform_variants_env(ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCFRONT", VCFRONT_MODEL, ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCPDU", VCPDU_MODEL, ALL_PLATFORMS) |
    rig_platform_sim_lib_env("VCREAR", VCREAR_MODEL, ALL_PLATFORMS),
    resources = [
        "{}:enums-py".format(VCFRONT_MODEL),
        "{}:vcfront-py".format(VCFRONT_MODEL),
        "{}:sil-so".format(VCFRONT_MODEL),
        "{}:enums-py".format(VCPDU_MODEL),
        "{}:vcpdu-py".format(VCPDU_MODEL),
        "{}:sil-so".format(VCPDU_MODEL),
        "//sim/models/vehicle:python",
        "//sim/models/components:python",
        "//sim/models/components/asm330:python",
        "//sim/models/components/dc_load:python",
        "{}:enums-py".format(VCREAR_MODEL),
        "{}:vcrear-py".format(VCREAR_MODEL),
        "{}:sil-so".format(VCREAR_MODEL),
    ] +
    rig_platform_sim_lib_resources(VCFRONT_MODEL, ALL_PLATFORMS) +
    rig_platform_sim_lib_resources(VCPDU_MODEL, ALL_PLATFORMS) +
    rig_platform_sim_lib_resources(VCREAR_MODEL, ALL_PLATFORMS),
    visibility = ["PUBLIC"],
)
