load("//components/vc/rear:platforms.bzl", "VCREAR_PLATFORM_VARIANTS")
load("//sim/infra:defs.bzl", "rig_embedded_controller_model")

rig_embedded_controller_model(
    controller = "vcrear",
    class_name = "VcrearModel",
    component = "//components/vc/rear",
    platform_variants = VCREAR_PLATFORM_VARIANTS,
    model_target = "//sim/models/controllers/vcrear",
    python_srcs = [
        "__init__.py",
        "fixtures.py",
        "simple.py",
        "variants.py",
    ],
    runtime_modules = ["can", "core", "faults", "flash", "io", "swi", "system", "time", "timer_capture", "uart"],
    extra_deps = [
        "//components/vc/shared:headers",
    ],
    bindgen_headers = [
        "Module.h",
        "HW_gpio_componentSpecific.h",
        "drv_inputAD_componentSpecific.h",
        "drv_outputAD.h",
        "drv_outputAD_componentSpecific.h",
        "YamcanShared.h",
    ],
    bindgen_types = [
        "drv_inputAD_channelAnalog_E",
        "drv_outputAD_channelDigital_E",
        "HW_GPIO_pinmux_E",
        "CAN_data_T",
        "YamcanShared",
    ],
    enum_headers = [
        "HW_gpio_componentSpecific.h",
        "HW_tim.h",
        "drv_inputAD_componentSpecific.h",
        "drv_outputAD_componentSpecific.h",
    ],
    c_enums = [
        "drv_inputAD_channelAnalog_E:AnalogInput:DRV_INPUTAD_ANALOG_::upper",
        "HW_GPIO_pinmux_E:DigitalIo:HW_GPIO_::upper",
        "drv_outputAD_channelDigital_E:DigitalOutput:DRV_OUTPUTAD_DIGITAL_::upper",
        "HW_TIM_port_E:TimerPort:HW_TIM_PORT_::upper",
        "HW_TIM_channel_E:TimerChannel:HW_TIM_CHANNEL_::upper",
    ],
    enum_rust_enums = [
        "FmFault:Fault:Vcrear:Fault:camel",
    ],
)
