/**
 * @file HW_gpio_componentSpecific.c
 * @brief  Source code for GPIO firmware
 */

/******************************************************************************
 *                             I N C L U D E S
 ******************************************************************************/

// Firmware Includes
#include "HW_gpio.h"

const HW_GPIO_S HW_GPIO_pinmux[HW_GPIO_COUNT] = {
    [HW_GPIO_CAN1_RX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_8,
        .mode = GPIO_MODE_INPUT,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_NOSET,
    },
    [HW_GPIO_CAN1_TX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_9,
        .mode = GPIO_MODE_AF_PP,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINSET,
    },
    [HW_GPIO_CAN2_RX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_12,
        .mode = GPIO_MODE_INPUT,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_NOSET,
    },
    [HW_GPIO_CAN2_TX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_13,
        .mode = GPIO_MODE_AF_PP,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINSET,
    },
    [HW_GPIO_LED] = {
        .port = GPIOC,
        .pin = GPIO_PIN_13,
        .mode = GPIO_MODE_OUTPUT_PP,
        .speed = GPIO_SPEED_FREQ_LOW,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_PE2] = {
        .port = GPIOE,                     // From Pin Name column
        .pin = GPIO_PIN_2,                 // From Pin Number column
        .mode = GPIO_MODE_INPUT,            // Based on Type and Function
        .speed = GPIO_SPEED_FREQ_HIGH,      // Typical for fast signal handling
        .pull = GPIO_NOPULL,                // No pull specified
        .resetState = HW_GPIO_NOSET,        // Default reset state
    },
    //start
    [HW_GPIO_DIG_SPARE1] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_DIG_SPARE2] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_DIG_SPARE3] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_DIG_SPARE4] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_LED] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_SPARE1] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_SPARE2] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_SPARE3] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_SPARE4] = {
        .port = GPIOCC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_APPS_P1] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_APPS_P2] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_BR_POT] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_L_SHK_DISP] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_L_BR_TEMP] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_R_SHK_DISP] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_R_BR_TEMP] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_PU1] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_PU2] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_BR_PR] = {
        .port = GPIOB,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_ADC_BOARD_TEMP] = {
        .port = GPIOB,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_5V_FLT2] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_5V_EN2] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_5V_EN1] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_5V_FLT1] = {
        .port = GPIOE,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_CAN2_RX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_CAN2_TX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_MUX_SEL2] = {
        .port = GPIOD,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_MUX_SEL1] = {
        .port = GPIOD,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_HORN_EN] = {
        .port = GPIOD,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_BMS_LIGHT_EN] = {
        .port = GPIOD,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_IMD_LIGHT_EN] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_TSSI_G_EN] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_TSSI_R_EN] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_BR_LIGHT_EN] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_CAN1_RX] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_CAN1_TX] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_MCU_UART_EN] = {
        .port = GPIOA,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_MCU_UART_TX] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_MCU_UART_RX] = {
        .port = GPIOC,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_SPI_CS_IMU] = {
        .port = GPIOD,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_SPI_CS_SD] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_SPI_SCK] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_SPI_MISO] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_SPI_MOSI] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_TACH_FLOW] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_TACH_WHEELSPEED_R] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_TACH_WHEELSPEED_L] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_RUN_BUTTON] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    [HW_GPIO_COUNT] = {
        .port = GPIO,
        .pin = GPIO_PIN_,
        .mode = GPIO_MODE_,
        .speed = GPIO_SPEED_FREQ_,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
    
};
