config:
  prefix: app
  description: General definitions for applications and bootloaders
defs:
  lib_enabled:
    requires: 
      - app_start_addr
      - app_pcba_id
      - app_component_id
      - app_function_id
  start_addr:
    requires: 
      - app_lib_enabled
  pcba_id:
    requires: 
      - app_lib_enabled
  component_id:
    discreteValue: component_id
    requires: 
      - app_lib_enabled
  node_id:
    requires: 
      - app_lib_enabled
  function_id:
    discreteValue: function_id
    requires:
      - app_lib_enabled
  uds:
  validation_enabled:
    requires:
      - app_lib_enabled
  validate_crc_enabled:
    requires:
      - app_validation_enabled
  10kHz_task:
discreteValues:
  component_id:
    - debug
    - bmsw
    - bmsb
    - stw
    - vcpdu
    - vcfront
    - vcrear
  function_id:
    - bl
    - app
    - blu
