/**
 * @file HW_gpio_componentSpecific.c
 * @brief  Source code for GPIO firmware
 */

/******************************************************************************
 *                             I N C L U D E S
 ******************************************************************************/

// Firmware Includes
#include "HW_gpio.h"

const HW_GPIO_S HW_GPIO_pinmux[HW_GPIO_COUNT] = {
    [HW_GPIO_CAN1_RX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_8,
        .mode = GPIO_MODE_INPUT,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_NOSET,
    },
    [HW_GPIO_CAN1_TX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_9,
        .mode = GPIO_MODE_AF_PP,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINSET,
    },
    [HW_GPIO_CAN2_RX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_12,
        .mode = GPIO_MODE_INPUT,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_NOSET,
    },
    [HW_GPIO_CAN2_TX] = {
        .port = GPIOB,
        .pin = GPIO_PIN_13,
        .mode = GPIO_MODE_AF_PP,
        .speed = GPIO_SPEED_FREQ_HIGH,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINSET,
    },
    [HW_GPIO_LED] = {
        .port = GPIOB,
        .pin = GPIO_PIN_8,
        .mode = GPIO_MODE_OUTPUT_PP,
        .speed = GPIO_SPEED_FREQ_LOW,
        .pull = GPIO_NOPULL,
        .resetState = HW_GPIO_PINRESET,
    },
};



/*----------------------*/

[HW_GPIO_BMS2_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ACCUM_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP2_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BSPD_MEM] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_SPI_CS_SD] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_VCU3_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_MC_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP5_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP2_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP3_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP4_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP5_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_UVL_BATT] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_THERMISTERS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_HP_SPI_CS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_5V_VOLTAGE] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_DAC_BRAKE_IN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_5V_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
}
[HW_GPIO_ADC_LP1_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP6_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP7_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP8_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_ADC_LP9_SNS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BMS_STATUS] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_MUX_SEL1] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_MUX_SEL2] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_PUMP_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_PUMP_FAULT] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_FANHP_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_FANHP_FAULT] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_SPARE_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BMS4_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_OL_DETECT] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_RESET_5V] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_VCU_SFTY_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_CAN2_RX] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_CAN2_TX] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_VC1_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_VC2_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
}
[HW_GPIO_LP4_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_HP_SPI_CS_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_DIA_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_5V_FLT2] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_5V_EN1] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_5V_EN2] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_5V_FLT1] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_MUX_LP_SEL2] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_PWM1] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_PWM2] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_VCU1_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_VCU2_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP8_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_UART_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BMS_MEM] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_CAN1_RX] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_CAN1_TX] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
}
[HW_GPIO_SPI_CS_IMD] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_UART_TX_MCU_PP] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_UART_TX_MCU_IN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BMS3_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_MUX_LP_SEL1] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_HVE_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_COCKPIT_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP6_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BMS5_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BMS6_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP9_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP7_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_SCK_MCU] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_MISO_MCU] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_MOSI_MCU] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_SENSOR_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP3_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LED] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_LP1_LATCH] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_SHUTDOWN_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_BMS1_EN] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
},
[HW_GPIO_COUNT] = {
    .port = GPIOB,
    .pin = GPIO_PIN_8,
    .mode = GPIO_MODE_OUTPUT_PP,
    .speed = GPIO_SPEED_FREQ_LOW,
    .pull = GPIO_NOPULL,
    .resetState = HW_GPIO_PINRESET,
}
    

    

    the port is found under the D column, it is a letter A-E thats found after P... Example, the port for 'PE2' is 'E' therfore you will write  .port = GPIOE