load("//sim/infra:defs.bzl", "rig_model_python")

rig_model_python(
    srcs = [
        "__init__.py",
        "model.py",
    ],
    visibility = ["PUBLIC"],
)

export_file(
    name = "rust.rs",
    src = "rust.rs",
    visibility = ["PUBLIC"],
)
