load(":defs.bzl", "download_openocd_distribution", "openocd_tool", "openocd_distribution")

download_openocd_distribution(
    name = "dist-openocd",
    version = "0.12.0-6",
)

#openocd_tool(
#    name = "openocd",
#    version = "0.12.0-6",
#    visibility = ["//components/..."],
#)
