name: Clean Working dir, Pull Current Branch, and Retrive Branch Metadata

on:
  workflow_dispatch:
    outputs:
      sha:
        description: "The current branch's SHA"
        value: ${{ jobs.run.outputs.sha }}
      short-sha:
        description: "The current branch's short (7) SHA"
        value: ${{ jobs.run.outputs.short-sha }}

jobs:
  run:
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
      short-sha: ${{ steps.sha.outputs.short-sha }}
    steps:
      - name: Clean
        uses: AutoModality/action-clean@1077775f5ef0022fc3a9d6f93377921ea3701fa7
      - name: Pull Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: 'true'
          submodules: 'recursive'
      - name: Get SHA and SHA7
        id: sha
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT && \
          echo "short-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
