export_file(
    name = "pyproject",
    src = "pyproject.toml",
    visibility = ["PUBLIC"],
)

export_file(
    name = "uv-lock",
    src = "uv.lock",
    visibility = ["PUBLIC"],
)

genrule(
    name = "uv-project",
    out = "uv-project",
    cmd = "mkdir -p $OUT && cp $(location :pyproject) $OUT/pyproject.toml && cp $(location :uv-lock) $OUT/uv.lock",
    visibility = ["PUBLIC"],
)
