[package]
name = "log-offloader"
version = "0.1.0"
edition = "2024"

[dependencies]
clap        = { workspace = true }
anyhow      = { workspace = true }
serde_json  = { workspace = true }
bin-logger   = { path = "..../libs/bin-logger" }
