/**
 * @file drv_outputAD_componentSpecific.h
 * @brief Header file for the component specific output driver
 */

#pragma once

/******************************************************************************
 *                             T Y P E D E F S
 ******************************************************************************/

typedef enum
{
    DRV_OUTPUTAD_ANALOG_COUNT,
} drv_outputAD_channelAnalog_E;

typedef enum
{
    DRV_OUTPUTAD_BMS1_EN = 0U,
    DRV_OUTPUTAD_BMS2_EN,
    DRV_OUTPUTAD_BMS3_EN,
    DRV_OUTPUTAD_BMS4_EN,
    DRV_OUTPUTAD_BMS5_EN,
    DRV_OUTPUTAD_BMS6_EN,
    DRV_OUTPUTAD_LP1_LATCH,
    DRV_OUTPUTAD_LP2_LATCH,
    DRV_OUTPUTAD_LP3_LATCH,
    DRV_OUTPUTAD_LP4_LATCH,
    DRV_OUTPUTAD_LP5_LATCH,
    DRV_OUTPUTAD_LP6_LATCH,
    DRV_OUTPUTAD_LP7_LATCH,
    DRV_OUTPUTAD_LP8_LATCH,
    DRV_OUTPUTAD_LP9_LATCH,
    DRV_OUTPUTAD_PUMP_FAULT,
    DRV_OUTPUTAD_FAN_FAULT,
    DRV_OUTPUTAD_ACCUM_EN,
    DRV_OUTPUTAD_5V_NEN1,
    DRV_OUTPUTAD_5V_NEN2,
    DRV_OUTPUTAD_VCU1_EN,
    DRV_OUTPUTAD_VCU2_EN,
    DRV_OUTPUTAD_VCU3_EN,
    DRV_OUTPUTAD_MC_EN,
    DRV_OUTPUTAD_MUX2_SEL1,
    DRV_OUTPUTAD_MUX2_SEL2,
    DRV_OUTPUTAD_PUMP_EN,
    DRV_OUTPUTAD_FAN_EN,
    DRV_OUTPUTAD_SPARE_EN,
    DRV_OUTPUTAD_VCU_SFTY_EN,
    DRV_OUTPUTAD_VC1_EN,
    DRV_OUTPUTAD_VC2_EN,
    DRV_OUTPUTAD_HP_SNS_EN,
    DRV_OUTPUTAD_DIA_EN,
    DRV_OUTPUTAD_SHUTDOWN_EN,
    DRV_OUTPUTAD_MUX_LP_SEL1,
    DRV_OUTPUTAD_MUX_LP_SEL2,
#if FEATURE_IS_ENABLED(FEATURE_PUMP_FULL_BEANS)
    DRV_OUTPUTAD_PWM1,
#endif
    DRV_OUTPUTAD_PWM2,
    DRV_OUTPUTAD_UART_EN,
    DRV_OUTPUTAD_HVE_EN,
    DRV_OUTPUTAD_COCKPIT_EN,
    DRV_OUTPUTAD_SENSOR_EN,
    DRV_OUTPUTAD_OL_DETECT,
    DRV_OUTPUTAD_DIGITAL_LED,
    DRV_OUTPUTAD_DIGITAL_COUNT,
} drv_outputAD_channelDigital_E;
