load("//tools/uv/defs.bzl", "uv_tool")

[
    export_file(
        name = file, 
        src = file, 
        visibility = ["PUBLIC"],
    )
    for file in [
        "configurator.py",
        "templates/drv_inputAD_componentSpecific.h.mako",
        "templates/drv_inputAD_componentSpecific.c.mako",
    ]
]

uv_tool(
    name = "configurator_tool",
    pyproject_file = "pyproject.toml",
    lock_file = "uv.lock",
    srcs = [ "configurator.py", ],
    visibility = ["PUBLIC"],
)

export_file(
    name = "defs",
    src = "defs.bzl",
    visibility = ["PUBLIC"],
)
