/*
 * CANIO-rx_helper.c
 * CAN Receive Helper functions
 */

#pragma once

/******************************************************************************
 *                             t y p e d e f s
 ******************************************************************************/

// Should eventually be autogenerated (and efficient)
typedef enum
{
    CANRX_NODE_BMSW0 = 0U,
    CANRX_NODE_BMSW1,
    CANRX_NODE_BMSW2,
    CANRX_NODE_BMSW3,
    CANRX_NODE_BMSW4,
    CANRX_NODE_BMSW5,
    CANRX_NODE_BMSW_COUNT,
} CANRX_NODE_BMSW_E;
