load("//sim/bindings:defs.bzl", "RIG_RUNTIME_RUST_ENV")

filegroup(
    name = "binding",
    srcs = glob(["*.c", "*.h"]),
    visibility = ["PUBLIC"],
)

prebuilt_cxx_library(
    name = "headers",
    header_only = True,
    header_namespace = "",
    exported_headers = {
        file: file
        for file in glob(["*.h"])
    },
    visibility = ["PUBLIC"],
)

filegroup(
    name = "python",
    srcs = glob(["*.py"]),
    visibility = ["PUBLIC"],
)

export_file(
    name = "gen-python-model",
    src = "gen_python_model.py",
    visibility = ["PUBLIC"],
)

rust_test(
    name = "runtime_unit",
    crate = "rig_runtime",
    crate_root = "ffi.rs",
    edition = "2024",
    srcs = glob(["*.rs"]),
    env = {
        name: "$(location {})".format(target)
        for name, target in RIG_RUNTIME_RUST_ENV.items()
    },
    visibility = ["PUBLIC"],
)

export_file(
    name = "runtime-src",
    src = "runtime.rs",
    visibility = ["PUBLIC"],
)

[
    export_file(
        name = file,
        src = file,
        visibility = ["PUBLIC"],
    )
    for file in glob(["*.rs"])
]

genrule(
    name = "runtime-so",
    out = "librig_runtime.so",
    cmd = " ".join([
        "{}=$PWD/$(location {})".format(name, target)
        for name, target in RIG_RUNTIME_RUST_ENV.items()
    ]) +
    " rustc --edition=2024 --crate-name rig_runtime --crate-type cdylib " +
    "$(location :ffi.rs) -o $OUT -C link-arg=-lm",
    visibility = ["PUBLIC"],
)

[
    export_file(name = file, src = file, visibility = ["PUBLIC"])
    for file in glob(["*.c", "*.h", "*.py"])
]
