load("@toolchains//gcc/defs.bzl", "generate_asms", "generate_stripped_asms")
load("//components/shared/code/defs.bzl", "remap_headers", "shared_code_library")
load("//drive-stack/defs.bzl", "deployable_target")
load("//drive-stack/conUDS/defs.bzl", "conUDS_download")
load("//drive-stack/ota-agent/defs.bzl", "ota_agent")
load("//embedded/openocd/defs.bzl", "openocd_run")
load("//embedded/platforms/stm32/f1:defs.bzl", "stm32f1_hal")
load("//tools/yamcan/defs.bzl", "generate_code")
load("//tools/hextools/defs.bzl", "inject_crc")
load(
    "//components/vehicle_platform:defs.bzl",
    "add_platform_deploy_targets",
    "generate_feature_trees_by_platform",
    "platform_selected_codegen_srcs",
    "platform_selected_targets",
)
load(
    "//components/vehicle_platform:platforms.bzl",
    "PLATFORMS",
    "platform_output_name",
)

TOOLCHAIN = "@toolchains//:gcc-14.2.rel1-arm-none-eabi"
APP_START_ADDR = 0x08002000
APP_NAME = "bmsb"

platform_variants = [
    (PLATFORMS.CFR25, 1),
    (PLATFORMS.CFR26, 1),
]

compiler_flags = [
    "-std=c11",
    "-mthumb",
    "-mcpu=cortex-m3",
    "-mfloat-abi=soft",
    "-msoft-float",
    "-nostdlib",
    "-nostartfiles",
    "-specs=nano.specs",
    "-ffunction-sections",
    "-fdata-sections",
    "-fshort-enums",
    "-funsigned-char",
    # "-DLD_USE_STACK",
    "-DLD_USE_HEAP",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-Wfloat-equal",
    "-Wcast-align",
    "-Wlogical-op",
    "-Winline",
    "-Wshadow",
    "-Winit-self",
    "-Wmissing-prototypes",
    "-Wunused-function",
    "-Wpointer-arith",
    "-Wno-type-limits",
    "-Wno-unused-local-typedefs",
    "-Wundef",
    "-Wconversion",
    "-ggdb3",
    "-g3",
    "-Og",
]

linker_flags = [
    "-Wl,--gc-sections",
    # "--print-gc-sections",
    "-Wl,--relax",
    "-Wl,--print-memory-usage",
    "-Wl,--stats",
]

cxx_library(
    name = "FreeRTOS",
    _cxx_toolchain = TOOLCHAIN,
    compiler_flags = compiler_flags,
    srcs = [
        "//embedded/libs:FreeRTOS-src[Source/croutine.c]",
        "//embedded/libs:FreeRTOS-src[Source/event_groups.c]",
        "//embedded/libs:FreeRTOS-src[Source/list.c]",
        "//embedded/libs:FreeRTOS-src[Source/portable/GCC/ARM_CM3/port.c]",
        "//embedded/libs:FreeRTOS-src[Source/queue.c]",
        "//embedded/libs:FreeRTOS-src[Source/tasks.c]",
        "//embedded/libs:FreeRTOS-src[Source/timers.c]",
    ],
    header_namespace = "",
    exported_headers = {
        "FreeRTOS.h": "//embedded/libs:FreeRTOS-src[Source/include/FreeRTOS.h]",
        "croutine.h": "//embedded/libs:FreeRTOS-src[Source/include/croutine.h]",
        "deprecated_definitions.h": "//embedded/libs:FreeRTOS-src[Source/include/deprecated_definitions.h]",
        "event_groups.h": "//embedded/libs:FreeRTOS-src[Source/include/event_groups.h]",
        "list.h": "//embedded/libs:FreeRTOS-src[Source/include/list.h]",
        "mpu_wrappers.h": "//embedded/libs:FreeRTOS-src[Source/include/mpu_wrappers.h]",
        "portable.h": "//embedded/libs:FreeRTOS-src[Source/include/portable.h]",
        "portmacro.h": "//embedded/libs:FreeRTOS-src[Source/portable/GCC/ARM_CM3/portmacro.h]",
        "projdefs.h": "//embedded/libs:FreeRTOS-src[Source/include/projdefs.h]",
        "queue.h": "//embedded/libs:FreeRTOS-src[Source/include/queue.h]",
        "stack_macros.h": "//embedded/libs:FreeRTOS-src[Source/include/stack_macros.h]",
        "semphr.h": "//embedded/libs:FreeRTOS-src[Source/include/semphr.h]",
        "stream_buffer.h": "//embedded/libs:FreeRTOS-src[Source/include/stream_buffer.h]",
        "task.h": "//embedded/libs:FreeRTOS-src[Source/include/task.h]",
        "timers.h": "//embedded/libs:FreeRTOS-src[Source/include/timers.h]",
        "FreeRTOSConfig.h": "include/FreeRTOSConfig.h",
    },
    exported_deps = [":CMSIS-hal-f105"],
)

generate_feature_trees_by_platform(
    platform_variants = platform_variants,
    app_name = APP_NAME,    srcs_by_platform = {
        PLATFORMS.CFR25: {
            "variants.yaml": "variants.yaml",
            "BMS_FeatureSels.yaml": "//components/shared:FeatureSels/BMS_CFR25_FeatureSels.yaml",
            "BMS_FeatureDefs.yaml": "//components/shared:FeatureDefs/BMS_FeatureDefs.yaml",
            "STM32F105_FeatureSels.yaml": "//components/shared:FeatureSels/STM32F105_FeatureSels.yaml",
            "Controller_FeatureDefs.yaml": "//components/shared:FeatureDefs/Controller_FeatureDefs.yaml",
            "APP_V1_FeatureSels.yaml": "//components/shared:FeatureSels/APP_V1_FeatureSels.yaml",
            "Application_FeatureDefs.yaml": "//components/shared:FeatureDefs/Application_FeatureDefs.yaml",
            "NVM_FeatureDefs.yaml": "//components/shared:FeatureDefs/NVM_FeatureDefs.yaml",
            "hw_FeatureDefs.yaml": "//components/shared/code:HW/hw_FeatureDefs.yaml",
            "FeatureDefs.yaml": "FeatureDefs.yaml",
            "FeatureSels.yaml": "FeatureSels.yaml",
        },
        PLATFORMS.CFR26: {
            "variants.yaml": "variants.yaml",
            "BMS_FeatureSels.yaml": "//components/shared:FeatureSels/BMS_CFR26_FeatureSels.yaml",
            "BMS_FeatureDefs.yaml": "//components/shared:FeatureDefs/BMS_FeatureDefs.yaml",
            "STM32F105_FeatureSels.yaml": "//components/shared:FeatureSels/STM32F105_FeatureSels.yaml",
            "Controller_FeatureDefs.yaml": "//components/shared:FeatureDefs/Controller_FeatureDefs.yaml",
            "APP_V1_FeatureSels.yaml": "//components/shared:FeatureSels/APP_V1_FeatureSels.yaml",
            "Application_FeatureDefs.yaml": "//components/shared:FeatureDefs/Application_FeatureDefs.yaml",
            "NVM_FeatureDefs.yaml": "//components/shared:FeatureDefs/NVM_FeatureDefs.yaml",
            "hw_FeatureDefs.yaml": "//components/shared/code:HW/hw_FeatureDefs.yaml",
            "FeatureDefs.yaml": "FeatureDefs.yaml",
            "FeatureSels.yaml": "FeatureSels.yaml",
        },
    },
)

prebuilt_cxx_library(
    name = "build-headers",
    header_only = True,
    header_namespace = "",
    exported_headers = {
        "BuildDefines.h": "HW/include/BuildDefines.h",
    } | remap_headers(["HW/include/"]) | remap_headers(["include/"]),
    exported_deps = platform_selected_targets(platform_variants),
)

compiler_flags += ["-include", "BuildDefines.h"]

generate_code(
    name = "network",
    _cxx_toolchain = TOOLCHAIN,
    compiler_flags = compiler_flags + ["-Wno-float-conversion", "-Wno-sign-conversion"],
    node = APP_NAME,
    network_dep = "//network:network",
    library_deps = [
        ":build-headers",
        ":hal-f105",
        ":FreeRTOS",
        "//components/shared/code:headers",
        "//components/shared/code/RTOS:headers",
    ],
)

cxx_library(
    name = "udsServer",
    _cxx_toolchain = TOOLCHAIN,
    compiler_flags = compiler_flags + [
        "-Wno-missing-prototypes",
        "-Wno-unused-parameter",
        "-DBYTE_ORDER=_BYTE_ORDER",
        "-DLITTLE_ENDIAN=_LITTLE_ENDIAN",
        "-Wno-inline",
        "-Wno-conversion",
    ],
    srcs = [
        "//embedded/libs:isotp-src[isotp.c]",
        "//embedded/libs/uds:lib_udsServer.c",
    ],
    header_namespace = "",
    exported_headers = {
        "lib_uds.h": "//embedded/libs/uds:lib_uds.h",
    },
    deps = [
        ":network",
        ":build-headers",
        "//components/shared/code:headers",
    ],
    headers = {
        "uds_componentSpecific.h": "include/uds_componentSpecific.h",
        "isotp.h": "//embedded/libs:isotp-src[include/isotp.h]",
        "isotp_config.h": "//embedded/libs:isotp-src[include/isotp_config.h]",
        "isotp_defines.h": "//embedded/libs:isotp-src[include/isotp_defines.h]",
        "isotp_user.h": "//embedded/libs:isotp-src[include/isotp_user.h]",
    },
)

[
    stm32f1_hal(
        name = "hal-" + name,
        toolchain = TOOLCHAIN,
        compiler_flags = compiler_flags,
        variant = variant,
        hal_conf_header = "HW/include/stm32f1xx_hal_conf.h",
        additional_deps = [
            ":build-headers",
        ],
        config = {
            "linker": {
                "useDefault": True,
            },
            "drivers": {
                "adc": {},
                "adc_ex": {},
                "can": {},
                "cortex": {},  # required
                "dma": {},
                "exti": {},
                "flash": {},
                "gpio": {},
                "i2c": {},
                "pwr": {},
                "rcc": {},
                "rcc_ex": {},  # required
                "spi": {
                    "use_ll": True,
                },
                "tim": {},
                "tim_ex": {},  # required with tim,
            },
        },
    )
    for name, variant in [
        ("f103", "stm32f103"),
        ("f105", "stm32f105"),
    ]
]

[
    cxx_genrule(
        name = "linkscript-" + variant,
        _cxx_toolchain = TOOLCHAIN,
        cmd = "set -o pipefail && $(cpp) -P -undef {}".format(" ".join(compiler_flags)) +
              " -include BuildDefines.h linkscript | sed -e '/^#.\\+$/d' > ${OUT}",
        out = "linkscript",
        srcs = platform_selected_codegen_srcs(platform_variants, {
            "linkscript": "//embedded/platforms/stm32/f1/" + variant + ":" + script,
            "BuildDefines.h": "HW/include/BuildDefines.h",
            "FeatureDefines.h": "//tools/feature-tree:FeatureDefines.h",
        }),
    )
    for variant, script in [
        ("f103", "stm32f103c8.ld"),
        ("f105", "stm32f105vc.ld"),
    ]
]

component_headers = remap_headers(["include/", "HW/include/"])

cxx_binary(
    name = "elf",
    _cxx_toolchain = TOOLCHAIN,
    compiler_flags = compiler_flags,
    linker_flags = compiler_flags + linker_flags + ["-T", "$(location :linkscript-f105)"] + [
        # "$(location :FreeRTOS[objects][FreeRTOS/Source/croutine.c.o])",
        # "$(location :FreeRTOS[objects][FreeRTOS/Source/event_groups.c.o])",
        # "$(location :FreeRTOS[objects][FreeRTOS/Source/list.c.o])",
        # "$(location :FreeRTOS[objects][FreeRTOS/Source/queue.c.o])",
        # "$(location :FreeRTOS[objects][FreeRTOS/Source/tasks.c.o])",
        # "$(location :FreeRTOS[objects][FreeRTOS/Source/timers.c.o])",
        # "$(location :FreeRTOS[objects][FreeRTOS/Source/portable/GCC/ARM_CM3/port.c.o])",
    ],
    executable_name = APP_NAME + ".elf",
    srcs =
        glob(["src/*.c", "HW/*.c"]) + [
            "//components/shared/code:DRV/drv_hih.c",
            "//components/shared/code:DRV/drv_inputAD.c",
            "//components/shared/code:DRV/drv_io.c",
            "//components/shared/code:DRV/drv_outputAD.c",
            "//components/shared/code:DRV/drv_userInput.c",
            "//components/shared/code:DRV/drv_timer.c",
            "//components/shared/code:HW/HW.c",
            "//components/shared/code:HW/HW_adc.c",
            "//components/shared/code:HW/HW_can.c",
            "//components/shared/code:HW/HW_flash.c",
            "//components/shared/code:HW/HW_gpio.c",
            "//components/shared/code:HW/HW_i2c.c",
            "//components/shared/code:HW/HW_tim.c",
            "//components/shared/code:app/CAN/CANIO-rx.c",
            "//components/shared/code:app/CAN/CANIO-tx.c",
            "//components/shared/code:libs/LIB_app.c",
            "//components/shared/code:libs/lib_simpleFilter.c",
            "//components/shared/code:libs/lib_interpolation.c",
            "//components/shared/code:libs/lib_nvm.c",
            "//components/shared/code:libs/lib_swFuse.c",
            "//components/shared/code:libs/lib_thermistors.c",
            "//components/shared/code:app/app_faultManager.c",
            "//components/shared/code:libs/Utility.c",
            ("//components/shared/code/RTOS:FreeRTOSResources.c", ["-Wno-missing-prototypes"]),
            "//components/shared/code/RTOS:FreeRTOS_SWI.c",
            "//components/shared/code/RTOS:Module.c",
            "//embedded/libs:libcrc.c",
            select({
                "DEFAULT": "//embedded/platforms/stm32/f1/f105:startup_stm32f105vc.S",
            }),
        ],
    header_namespace = "",
    headers = {
        "lib_atomic.h": "//embedded/libs:lib_atomic.h",
        "libcrc.h": "//embedded/libs:libcrc.h",
    } | component_headers,
    include_directories = [
        "include/",
        "HW/include/",
        "RTOS/include/",
    ],
    deps = [
        ":hal-f105",
        ":udsServer",
        ":FreeRTOS",
        ":network",
        ":build-headers",
        "//components/shared/code:headers",
        "//components/shared/code/RTOS:headers",
    ],
)

generate_asms(
    name = "asm",
    binary = ":elf",
)

generate_stripped_asms(
    name = "asms",
    targets = [
        ":elf",
        ":FreeRTOS",
        ":udsServer",
        ":hal-f105",
        ":network",
    ],
    toolchain = TOOLCHAIN,
)

cxx_genrule(
    name = "bin",
    _cxx_toolchain = TOOLCHAIN,
    srcs = [":elf"],
    out = APP_NAME + ".bin",
    cmd = "$(objcopy) -O binary ${SRCS} ${OUT}",
)

inject_crc(
    name = "bin_crc",
    src = ":bin",
    out = APP_NAME + "_crc.bin",
    start_address = APP_START_ADDR,
    visibility = ["PUBLIC"],
)
alias(
    name = APP_NAME,
    actual = ":bin",
)

add_platform_deploy_targets(
    platform_variants = platform_variants,
    app_name = APP_NAME,
)

[
    openocd_run(
        name = "gdb-{}".format(platform_output_name(platform)),
        toolchain = TOOLCHAIN,
        src = ":elf",
        interface = "stlink",
        mcu = "stm32f103c8",
    )
    for platform, _variant in platform_variants
]
