name: Build and Archive

on:
  workflow_call:
    inputs:
      build-targets:
        description: "The build targets to send scons"
        required: true
        type: string
      flags:
        description: "Build flags"
        default: "-j32"
        type: string
      build-type:
        description: "'platform' or 'targets' build"
        required: true
        type: string
      artifact-name:
        description: "Artifact name"
        default: "artifact"
        type: string
      ref:
        description: "The ref to build"
        type: string
      container:
        description: "The cotainer to use"
        default: "ubuntu-noble-lts:v1.0.0"
        type: string
    outputs:
      archive-url:
        description: "The link to the github archive of the build artifacts"
        value: ${{ jobs.build.outputs.archive-url }}

jobs:
  build:
    runs-on: self-hosted
    container: 
      image: docker://ghcr.io/concordia-fsae/containers/${{ inputs.container }}
    outputs:
      archive-url: ${{ steps.build.outputs.archive-url }}
    steps:
      - name: Clean
        uses: AutoModality/action-clean@1077775f5ef0022fc3a9d6f93377921ea3701fa7
      - name: Pull Branch
        uses: actions/checkout@v4
        with:
          repository: concordia-fsae/firmware
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          show-progress: 'true'
          submodules: 'recursive'
      - name: Build Targets
        id: build
        uses: concordia-fsae/firmware/.github/actions/build/@master
        with:
          build-targets: ${{ inputs.build-targets }}
          flags: ${{ inputs.flags }}
          build-type: ${{ inputs.build-type }}
          artifact-name: ${{ inputs.artifact-name }}

