name: Build and Archive

on:
  workflow_call:
    inputs:
      build-targets:
        description: "The build targets to send scons"
        required: true
        type: string
      flags:
        description: "Build flags"
        default: "-j32"
        type: string
      build-type:
        description: "'platform' or 'targets' build"
        required: true
        type: string
    outputs:
      build-artifacts-link:
        description: "The link to the github archive of the build artifacts"
        value: ${{ jobs.run.outputs.archive-url }}
      sha:
        description: "The current branch's SHA"
        value: ${{ jobs.run.outputs.sha }}
      short-sha:
        description: "The current branch's short (7) SHA"
        value: ${{ jobs.run.outputs.short-sha }}

jobs:
  run:
    runs-on: self-hosted
    container: 
      image: docker://ghcr.io/concordia-fsae/containers/ubuntu-noble-lts:v1.0.0
    outputs:
      archive-url: ${{ steps.archive.outputs.archive-url }}
      sha: ${{ steps.sha.outputs.sha }}
      short-sha: ${{ steps.sha.outputs.short-sha }}
    steps:
      - name: Clean
        uses: AutoModality/action-clean@1077775f5ef0022fc3a9d6f93377921ea3701fa7
      - name: Pull Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: 'true'
          submodules: 'recursive'
      - name: Get SHA and SHA7
        id: sha
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT && \
          echo "short-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build Targets
        id: build
        run: |
          scons --${{ inputs.build-type }}=${{ inputs.build-targets }} ${{ inputs.flags }}
      - name: Archive Artifacts
        id: archive
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: platform-artifacts/

