name: 'Build All Firmware'

on:
  pull_request:
    branches: [ master, comp* ]
  push:
    branches: [ master, comp* ]

jobs:
  generate-dbc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read Buck2 Version
        id: buck2_version
        shell: bash
        run: |
          buck2_version="$(awk -F'=' '/^buck2_version/ {gsub(/[[:space:]]/, "", $2); print $2}' .buckleconfig.toml)"
          echo "buck2_version=$buck2_version" >> "$GITHUB_OUTPUT"
      - name: Install Buck2
        uses: dtolnay/install-buck2@latest
        with:
          version: ${{ steps.buck2_version.outputs.buck2_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Build Stack
        run: buck2 build //network:dbc --out dbc/
      - name: Archive Artifacts
        id: archive
        uses: actions/upload-artifact@v4
        with:
          name: dbc
          path: dbc/
  generate-manifest-uds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read Buck2 Version
        id: buck2_version
        shell: bash
        run: |
          buck2_version="$(awk -F'=' '/^buck2_version/ {gsub(/[[:space:]]/, "", $2); print $2}' .buckleconfig.toml)"
          echo "buck2_version=$buck2_version" >> "$GITHUB_OUTPUT"
      - name: Install Buck2
        uses: concordia-fsae/install-buck2@latest
        with:
          release: ${{ steps.buck2_version.outputs.buck2_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Build Stack
        run: buck2 build //network:manifest-uds --out manifest-uds.yaml
      - name: Archive Artifacts
        id: archive
        uses: actions/upload-artifact@v4
        with:
          name: manifest-uds.yaml
          path: manifest-uds.yaml
  cfr-firmware:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
          - macos-15
          # TODO: Bringup support
          # - windows-2022
          # - windows-11-arm
        target:
          - cfr25
          - cfr26
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read Buck2 Version
        id: buck2_version
        shell: bash
        run: |
          buck2_version="$(awk -F'=' '/^buck2_version/ {gsub(/[[:space:]]/, "", $2); print $2}' .buckleconfig.toml)"
          echo "buck2_version=$buck2_version" >> "$GITHUB_OUTPUT"
      - name: Install Buck2
        uses: concordia-fsae/install-buck2@latest
        with:
          release: ${{ steps.buck2_version.outputs.buck2_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Build Stack
        run: buck2 build :${{ matrix.target }}-embedded -j32 --out builds/
      - name: Archive Artifacts
        if: ${{ matrix.runner == 'ubuntu-24.04' }}
        id: archive
        uses: actions/upload-artifact@v4
        with:
          name: embedded-${{ matrix.target }}
          path: builds/
  cfr-drive-stack:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-24.04, ubuntu-24.04-arm,]
                  # TODO: Bringup support
                  # macos-15, macos-14
                  # windows-2022, windows-11-arm, ]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read Buck2 Version
        id: buck2_version
        shell: bash
        run: |
          buck2_version="$(awk -F'=' '/^buck2_version/ {gsub(/[[:space:]]/, "", $2); print $2}' .buckleconfig.toml)"
          echo "buck2_version=$buck2_version" >> "$GITHUB_OUTPUT"
      - name: Install Buck2
        uses: concordia-fsae/install-buck2@latest
        with:
          release: ${{ steps.buck2_version.outputs.buck2_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Add ARM64 Toolchain
        run: rustup target add aarch64-unknown-linux-gnu
      - name: Build Stack
        run: buck2 build //drive-stack:cfr26-stack -j32 --out builds/
      - name: Archive Artifacts
        if: ${{ matrix.runner == 'ubuntu-24.04' }}
        id: archive
        uses: actions/upload-artifact@v4
        with:
          name: drive-stack-arm64
          path: builds/
  drive-tools:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-24.04, ubuntu-24.04-arm,]
                  # TODO: Bringup support
                  # macos-15, macos-14
                  # windows-2022, windows-11-arm, ]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read Buck2 Version
        id: buck2_version
        shell: bash
        run: |
          buck2_version="$(awk -F'=' '/^buck2_version/ {gsub(/[[:space:]]/, "", $2); print $2}' .buckleconfig.toml)"
          echo "buck2_version=$buck2_version" >> "$GITHUB_OUTPUT"
      - name: Install Buck2
        uses: concordia-fsae/install-buck2@latest
        with:
          release: ${{ steps.buck2_version.outputs.buck2_version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Build Tools
        run: buck2 build //drive-stack/conUDS -j32 --out builds/conUDS &&
             buck2 build //drive-stack/net-detec -j32 --out builds/net-detec &&
             buck2 build //drive-stack/ota-agent -j32 --out builds/ota-agent
      - name: Build Manifests
        run: buck2 build //network:manifest-uds -j32 --out builds/manifest-uds.yaml
      - name: Archive Artifacts
        id: archive
        uses: actions/upload-artifact@v4
        with:
          name: drive-tools-${{ matrix.runner }}
          path: builds/
  compare-cfr-embedded:
    strategy:
      fail-fast: false
      matrix:
        artifact: 
          - embedded-cfr25
          - embedded-cfr26
          - drive-stack-arm64
    runs-on: ubuntu-latest
    needs:
      - cfr-firmware
      - cfr-drive-stack
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Compare artifacts and comment on PR
        uses: ./.github/actions/compare-artifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          artifact-name: ${{ matrix.artifact }}
